project_name: gowhoson
before:
  hooks:
    - go mod download
builds:
  - main: ./cmd/gowhoson
    binary: gowhoson
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    ldflags:
      - -s -w
      - -X main.gVersion={{.Version}} -X main.gGitcommit={{.ShortCommit}}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
archives:
  - replacements:
      darwin: darwin
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64
    name_template: '{{ .Binary }}_{{.Version}}_{{ .Os }}_{{ .Arch }}'
    format: tar.gz
    files:
      - LICENSE
      - README*
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
release:
  prerelease: auto
