before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    binary: gowhoson
    goos:
      - darwin
      - linux
    goarch:
      - amd64
    main: ./cmd/gowhoson
    ldflags: -s -w -X main.gVersion={{.Version}} -X main.gGitcommit={{.Commit}} -X main.gGoversion={{.Env.GOVERSION}}
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format: tar.gz
    name_template: '{{ .Binary }}_{{.Version}}_{{ .Os }}_{{ .Arch }}'
    files:
      - LICENSE
      - README*
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
