version: 2

project_name: gowhoson
before:
  hooks:
    - go mod download
builds:
  - main: ./cmd/gowhoson
    binary: gowhoson
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    ldflags:
      - -s -w
      - -X main.gVersion={{.Version}} -X main.gGitcommit={{.ShortCommit}}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
archives:
  - format: tar.gz
    name_template: '{{ .Binary }}_{{.Version}}_{{ .Os }}_{{ .Arch }}'
    files:
      - LICENSE
      - README*
snapshot:
  version_template: "{{ incpatch .Version }}-next"
release:
  prerelease: auto
