version: 2
project_name: gowhoson
before:
  hooks:
    - go mod tidy
    - go mod download
builds:
  - main: ./cmd/gowhoson
    binary: gowhoson
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    ldflags:
      - -s -w
      - -X main.gVersion={{.Version}} -X main.gGitcommit={{.ShortCommit}}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
archives:
  - formats: [ 'tar.gz' ]
    name_template: '{{ .Binary }}_{{.Version}}_{{ .Os }}_{{ .Arch }}'
    files:
      - LICENSE
      - README*
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort:
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^fix.{0,1}$'
release:
  prerelease: auto
