// Code generated by protoc-gen-go.
// source: whoson/sync.proto
// DO NOT EDIT!

/*
Package whoson is a generated protocol buffer package.

It is generated from these files:
	whoson/sync.proto

It has these top-level messages:
	WSRequest
	WSResponse
	WSDumpRequest
	WSDumpResponse
*/
package whoson

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type WSRequest struct {
	Expire int64  `protobuf:"varint,1,opt,name=Expire" json:"Expire,omitempty"`
	IP     string `protobuf:"bytes,2,opt,name=IP" json:"IP,omitempty"`
	Data   string `protobuf:"bytes,3,opt,name=Data" json:"Data,omitempty"`
	Method string `protobuf:"bytes,4,opt,name=Method" json:"Method,omitempty"`
}

func (m *WSRequest) Reset()                    { *m = WSRequest{} }
func (m *WSRequest) String() string            { return proto.CompactTextString(m) }
func (*WSRequest) ProtoMessage()               {}
func (*WSRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type WSResponse struct {
	Rcode int32  `protobuf:"varint,1,opt,name=Rcode" json:"Rcode,omitempty"`
	Msg   string `protobuf:"bytes,2,opt,name=Msg" json:"Msg,omitempty"`
}

func (m *WSResponse) Reset()                    { *m = WSResponse{} }
func (m *WSResponse) String() string            { return proto.CompactTextString(m) }
func (*WSResponse) ProtoMessage()               {}
func (*WSResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type WSDumpRequest struct {
}

func (m *WSDumpRequest) Reset()                    { *m = WSDumpRequest{} }
func (m *WSDumpRequest) String() string            { return proto.CompactTextString(m) }
func (*WSDumpRequest) ProtoMessage()               {}
func (*WSDumpRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type WSDumpResponse struct {
	Rcode int32  `protobuf:"varint,1,opt,name=Rcode" json:"Rcode,omitempty"`
	Msg   string `protobuf:"bytes,2,opt,name=Msg" json:"Msg,omitempty"`
	Json  []byte `protobuf:"bytes,3,opt,name=Json,proto3" json:"Json,omitempty"`
}

func (m *WSDumpResponse) Reset()                    { *m = WSDumpResponse{} }
func (m *WSDumpResponse) String() string            { return proto.CompactTextString(m) }
func (*WSDumpResponse) ProtoMessage()               {}
func (*WSDumpResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto.RegisterType((*WSRequest)(nil), "whoson.WSRequest")
	proto.RegisterType((*WSResponse)(nil), "whoson.WSResponse")
	proto.RegisterType((*WSDumpRequest)(nil), "whoson.WSDumpRequest")
	proto.RegisterType((*WSDumpResponse)(nil), "whoson.WSDumpResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Sync service

type SyncClient interface {
	Set(ctx context.Context, in *WSRequest, opts ...grpc.CallOption) (*WSResponse, error)
	Del(ctx context.Context, in *WSRequest, opts ...grpc.CallOption) (*WSResponse, error)
	Dump(ctx context.Context, in *WSDumpRequest, opts ...grpc.CallOption) (*WSDumpResponse, error)
}

type syncClient struct {
	cc *grpc.ClientConn
}

func NewSyncClient(cc *grpc.ClientConn) SyncClient {
	return &syncClient{cc}
}

func (c *syncClient) Set(ctx context.Context, in *WSRequest, opts ...grpc.CallOption) (*WSResponse, error) {
	out := new(WSResponse)
	err := grpc.Invoke(ctx, "/whoson.sync/Set", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncClient) Del(ctx context.Context, in *WSRequest, opts ...grpc.CallOption) (*WSResponse, error) {
	out := new(WSResponse)
	err := grpc.Invoke(ctx, "/whoson.sync/Del", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncClient) Dump(ctx context.Context, in *WSDumpRequest, opts ...grpc.CallOption) (*WSDumpResponse, error) {
	out := new(WSDumpResponse)
	err := grpc.Invoke(ctx, "/whoson.sync/Dump", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Sync service

type SyncServer interface {
	Set(context.Context, *WSRequest) (*WSResponse, error)
	Del(context.Context, *WSRequest) (*WSResponse, error)
	Dump(context.Context, *WSDumpRequest) (*WSDumpResponse, error)
}

func RegisterSyncServer(s *grpc.Server, srv SyncServer) {
	s.RegisterService(&_Sync_serviceDesc, srv)
}

func _Sync_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/whoson.sync/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncServer).Set(ctx, req.(*WSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sync_Del_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncServer).Del(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/whoson.sync/Del",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncServer).Del(ctx, req.(*WSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sync_Dump_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WSDumpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncServer).Dump(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/whoson.sync/Dump",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncServer).Dump(ctx, req.(*WSDumpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Sync_serviceDesc = grpc.ServiceDesc{
	ServiceName: "whoson.sync",
	HandlerType: (*SyncServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Set",
			Handler:    _Sync_Set_Handler,
		},
		{
			MethodName: "Del",
			Handler:    _Sync_Del_Handler,
		},
		{
			MethodName: "Dump",
			Handler:    _Sync_Dump_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "whoson/sync.proto",
}

func init() { proto.RegisterFile("whoson/sync.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0xcf, 0xc8, 0x2f,
	0xce, 0xcf, 0xd3, 0x2f, 0xae, 0xcc, 0x4b, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83,
	0x08, 0x29, 0xc5, 0x73, 0x71, 0x86, 0x07, 0x07, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0x89,
	0x71, 0xb1, 0xb9, 0x56, 0x14, 0x64, 0x16, 0xa5, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x30, 0x07, 0x41,
	0x79, 0x42, 0x7c, 0x5c, 0x4c, 0x9e, 0x01, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x4c, 0x9e,
	0x01, 0x42, 0x42, 0x5c, 0x2c, 0x2e, 0x89, 0x25, 0x89, 0x12, 0xcc, 0x60, 0x11, 0x30, 0x1b, 0xa4,
	0xd7, 0x37, 0xb5, 0x24, 0x23, 0x3f, 0x45, 0x82, 0x05, 0x2c, 0x0a, 0xe5, 0x29, 0x99, 0x70, 0x71,
	0x81, 0x2c, 0x28, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x15, 0x12, 0xe1, 0x62, 0x0d, 0x4a, 0xce, 0x4f,
	0x81, 0x58, 0xc0, 0x1a, 0x04, 0xe1, 0x08, 0x09, 0x70, 0x31, 0xfb, 0x16, 0xa7, 0x43, 0x2d, 0x00,
	0x31, 0x95, 0xf8, 0xb9, 0x78, 0xc3, 0x83, 0x5d, 0x4a, 0x73, 0x0b, 0xa0, 0x4e, 0x53, 0xf2, 0xe1,
	0xe2, 0x83, 0x09, 0x90, 0x66, 0x14, 0xc8, 0xb1, 0x5e, 0xc5, 0xf9, 0x79, 0x60, 0xc7, 0xf2, 0x04,
	0x81, 0xd9, 0x46, 0xf3, 0x19, 0xb9, 0x58, 0x40, 0x81, 0x21, 0xa4, 0xc7, 0xc5, 0x1c, 0x9c, 0x5a,
	0x22, 0x24, 0xa8, 0x07, 0x09, 0x0e, 0x3d, 0x78, 0x58, 0x48, 0x09, 0x21, 0x0b, 0x41, 0xac, 0x54,
	0x62, 0x00, 0xa9, 0x77, 0x49, 0xcd, 0x21, 0x5e, 0xbd, 0x39, 0x17, 0x0b, 0xc8, 0xd1, 0x42, 0xa2,
	0x08, 0x59, 0x24, 0x5f, 0x49, 0x89, 0xa1, 0x0b, 0xc3, 0x34, 0x26, 0xb1, 0x81, 0xa3, 0xc9, 0x18,
	0x10, 0x00, 0x00, 0xff, 0xff, 0xa4, 0xed, 0x6c, 0xc5, 0xbb, 0x01, 0x00, 0x00,
}
