// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: pkg/whoson/sync.proto

package whoson

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WSRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Expire int64  `protobuf:"varint,1,opt,name=Expire,proto3" json:"Expire,omitempty"`
	IP     string `protobuf:"bytes,2,opt,name=IP,proto3" json:"IP,omitempty"`
	Data   string `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	Method string `protobuf:"bytes,4,opt,name=Method,proto3" json:"Method,omitempty"`
}

func (x *WSRequest) Reset() {
	*x = WSRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_whoson_sync_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WSRequest) ProtoMessage() {}

func (x *WSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_whoson_sync_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WSRequest.ProtoReflect.Descriptor instead.
func (*WSRequest) Descriptor() ([]byte, []int) {
	return file_pkg_whoson_sync_proto_rawDescGZIP(), []int{0}
}

func (x *WSRequest) GetExpire() int64 {
	if x != nil {
		return x.Expire
	}
	return 0
}

func (x *WSRequest) GetIP() string {
	if x != nil {
		return x.IP
	}
	return ""
}

func (x *WSRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *WSRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

type WSResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rcode int32  `protobuf:"varint,1,opt,name=Rcode,proto3" json:"Rcode,omitempty"`
	Msg   string `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *WSResponse) Reset() {
	*x = WSResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_whoson_sync_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WSResponse) ProtoMessage() {}

func (x *WSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_whoson_sync_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WSResponse.ProtoReflect.Descriptor instead.
func (*WSResponse) Descriptor() ([]byte, []int) {
	return file_pkg_whoson_sync_proto_rawDescGZIP(), []int{1}
}

func (x *WSResponse) GetRcode() int32 {
	if x != nil {
		return x.Rcode
	}
	return 0
}

func (x *WSResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type WSDumpRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WSDumpRequest) Reset() {
	*x = WSDumpRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_whoson_sync_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WSDumpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WSDumpRequest) ProtoMessage() {}

func (x *WSDumpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_whoson_sync_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WSDumpRequest.ProtoReflect.Descriptor instead.
func (*WSDumpRequest) Descriptor() ([]byte, []int) {
	return file_pkg_whoson_sync_proto_rawDescGZIP(), []int{2}
}

type WSDumpResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rcode int32  `protobuf:"varint,1,opt,name=Rcode,proto3" json:"Rcode,omitempty"`
	Msg   string `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	Json  []byte `protobuf:"bytes,3,opt,name=Json,proto3" json:"Json,omitempty"`
}

func (x *WSDumpResponse) Reset() {
	*x = WSDumpResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_whoson_sync_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WSDumpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WSDumpResponse) ProtoMessage() {}

func (x *WSDumpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_whoson_sync_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WSDumpResponse.ProtoReflect.Descriptor instead.
func (*WSDumpResponse) Descriptor() ([]byte, []int) {
	return file_pkg_whoson_sync_proto_rawDescGZIP(), []int{3}
}

func (x *WSDumpResponse) GetRcode() int32 {
	if x != nil {
		return x.Rcode
	}
	return 0
}

func (x *WSDumpResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *WSDumpResponse) GetJson() []byte {
	if x != nil {
		return x.Json
	}
	return nil
}

var File_pkg_whoson_sync_proto protoreflect.FileDescriptor

var file_pkg_whoson_sync_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x6b, 0x67, 0x2f, 0x77, 0x68, 0x6f, 0x73, 0x6f, 0x6e, 0x2f, 0x73, 0x79, 0x6e,
	0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x77, 0x68, 0x6f, 0x73, 0x6f, 0x6e, 0x22,
	0x5f, 0x0a, 0x09, 0x57, 0x53, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x45, 0x78,
	0x70, 0x69, 0x72, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x50, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x49, 0x50, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x4d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x22, 0x34, 0x0a, 0x0a, 0x57, 0x53, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x52, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x52,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x22, 0x0f, 0x0a, 0x0d, 0x57, 0x53, 0x44, 0x75, 0x6d, 0x70,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x4c, 0x0a, 0x0e, 0x57, 0x53, 0x44, 0x75, 0x6d,
	0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x52, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x52, 0x63, 0x6f, 0x64, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73,
	0x67, 0x12, 0x12, 0x0a, 0x04, 0x4a, 0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x4a, 0x73, 0x6f, 0x6e, 0x32, 0x9f, 0x01, 0x0a, 0x04, 0x73, 0x79, 0x6e, 0x63, 0x12, 0x2e,
	0x0a, 0x03, 0x53, 0x65, 0x74, 0x12, 0x11, 0x2e, 0x77, 0x68, 0x6f, 0x73, 0x6f, 0x6e, 0x2e, 0x57,
	0x53, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x77, 0x68, 0x6f, 0x73, 0x6f,
	0x6e, 0x2e, 0x57, 0x53, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x2e,
	0x0a, 0x03, 0x44, 0x65, 0x6c, 0x12, 0x11, 0x2e, 0x77, 0x68, 0x6f, 0x73, 0x6f, 0x6e, 0x2e, 0x57,
	0x53, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x77, 0x68, 0x6f, 0x73, 0x6f,
	0x6e, 0x2e, 0x57, 0x53, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x37,
	0x0a, 0x04, 0x44, 0x75, 0x6d, 0x70, 0x12, 0x15, 0x2e, 0x77, 0x68, 0x6f, 0x73, 0x6f, 0x6e, 0x2e,
	0x57, 0x53, 0x44, 0x75, 0x6d, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e,
	0x77, 0x68, 0x6f, 0x73, 0x6f, 0x6e, 0x2e, 0x57, 0x53, 0x44, 0x75, 0x6d, 0x70, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x61, 0x69, 0x2d, 0x67, 0x61, 0x2f, 0x67, 0x6f, 0x77,
	0x68, 0x6f, 0x73, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x77, 0x68, 0x6f, 0x73, 0x6f, 0x6e, 0x3b,
	0x77, 0x68, 0x6f, 0x73, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_whoson_sync_proto_rawDescOnce sync.Once
	file_pkg_whoson_sync_proto_rawDescData = file_pkg_whoson_sync_proto_rawDesc
)

func file_pkg_whoson_sync_proto_rawDescGZIP() []byte {
	file_pkg_whoson_sync_proto_rawDescOnce.Do(func() {
		file_pkg_whoson_sync_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_whoson_sync_proto_rawDescData)
	})
	return file_pkg_whoson_sync_proto_rawDescData
}

var file_pkg_whoson_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_whoson_sync_proto_goTypes = []interface{}{
	(*WSRequest)(nil),      // 0: whoson.WSRequest
	(*WSResponse)(nil),     // 1: whoson.WSResponse
	(*WSDumpRequest)(nil),  // 2: whoson.WSDumpRequest
	(*WSDumpResponse)(nil), // 3: whoson.WSDumpResponse
}
var file_pkg_whoson_sync_proto_depIdxs = []int32{
	0, // 0: whoson.sync.Set:input_type -> whoson.WSRequest
	0, // 1: whoson.sync.Del:input_type -> whoson.WSRequest
	2, // 2: whoson.sync.Dump:input_type -> whoson.WSDumpRequest
	1, // 3: whoson.sync.Set:output_type -> whoson.WSResponse
	1, // 4: whoson.sync.Del:output_type -> whoson.WSResponse
	3, // 5: whoson.sync.Dump:output_type -> whoson.WSDumpResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_whoson_sync_proto_init() }
func file_pkg_whoson_sync_proto_init() {
	if File_pkg_whoson_sync_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_whoson_sync_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WSRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_whoson_sync_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WSResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_whoson_sync_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WSDumpRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_whoson_sync_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WSDumpResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_whoson_sync_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_whoson_sync_proto_goTypes,
		DependencyIndexes: file_pkg_whoson_sync_proto_depIdxs,
		MessageInfos:      file_pkg_whoson_sync_proto_msgTypes,
	}.Build()
	File_pkg_whoson_sync_proto = out.File
	file_pkg_whoson_sync_proto_rawDesc = nil
	file_pkg_whoson_sync_proto_goTypes = nil
	file_pkg_whoson_sync_proto_depIdxs = nil
}
