// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: pkg/whoson/sync.proto

package whoson

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expire        int64                  `protobuf:"varint,1,opt,name=Expire,proto3" json:"Expire,omitempty"`
	IP            string                 `protobuf:"bytes,2,opt,name=IP,proto3" json:"IP,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	Method        string                 `protobuf:"bytes,4,opt,name=Method,proto3" json:"Method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WSRequest) Reset() {
	*x = WSRequest{}
	mi := &file_pkg_whoson_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WSRequest) ProtoMessage() {}

func (x *WSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_whoson_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WSRequest.ProtoReflect.Descriptor instead.
func (*WSRequest) Descriptor() ([]byte, []int) {
	return file_pkg_whoson_sync_proto_rawDescGZIP(), []int{0}
}

func (x *WSRequest) GetExpire() int64 {
	if x != nil {
		return x.Expire
	}
	return 0
}

func (x *WSRequest) GetIP() string {
	if x != nil {
		return x.IP
	}
	return ""
}

func (x *WSRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *WSRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

type WSResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rcode         int32                  `protobuf:"varint,1,opt,name=Rcode,proto3" json:"Rcode,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WSResponse) Reset() {
	*x = WSResponse{}
	mi := &file_pkg_whoson_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WSResponse) ProtoMessage() {}

func (x *WSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_whoson_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WSResponse.ProtoReflect.Descriptor instead.
func (*WSResponse) Descriptor() ([]byte, []int) {
	return file_pkg_whoson_sync_proto_rawDescGZIP(), []int{1}
}

func (x *WSResponse) GetRcode() int32 {
	if x != nil {
		return x.Rcode
	}
	return 0
}

func (x *WSResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type WSDumpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WSDumpRequest) Reset() {
	*x = WSDumpRequest{}
	mi := &file_pkg_whoson_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WSDumpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WSDumpRequest) ProtoMessage() {}

func (x *WSDumpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_whoson_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WSDumpRequest.ProtoReflect.Descriptor instead.
func (*WSDumpRequest) Descriptor() ([]byte, []int) {
	return file_pkg_whoson_sync_proto_rawDescGZIP(), []int{2}
}

type WSDumpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rcode         int32                  `protobuf:"varint,1,opt,name=Rcode,proto3" json:"Rcode,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	Json          []byte                 `protobuf:"bytes,3,opt,name=Json,proto3" json:"Json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WSDumpResponse) Reset() {
	*x = WSDumpResponse{}
	mi := &file_pkg_whoson_sync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WSDumpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WSDumpResponse) ProtoMessage() {}

func (x *WSDumpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_whoson_sync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WSDumpResponse.ProtoReflect.Descriptor instead.
func (*WSDumpResponse) Descriptor() ([]byte, []int) {
	return file_pkg_whoson_sync_proto_rawDescGZIP(), []int{3}
}

func (x *WSDumpResponse) GetRcode() int32 {
	if x != nil {
		return x.Rcode
	}
	return 0
}

func (x *WSDumpResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *WSDumpResponse) GetJson() []byte {
	if x != nil {
		return x.Json
	}
	return nil
}

var File_pkg_whoson_sync_proto protoreflect.FileDescriptor

const file_pkg_whoson_sync_proto_rawDesc = "" +
	"\n" +
	"\x15pkg/whoson/sync.proto\x12\x06whoson\"_\n" +
	"\tWSRequest\x12\x16\n" +
	"\x06Expire\x18\x01 \x01(\x03R\x06Expire\x12\x0e\n" +
	"\x02IP\x18\x02 \x01(\tR\x02IP\x12\x12\n" +
	"\x04Data\x18\x03 \x01(\tR\x04Data\x12\x16\n" +
	"\x06Method\x18\x04 \x01(\tR\x06Method\"4\n" +
	"\n" +
	"WSResponse\x12\x14\n" +
	"\x05Rcode\x18\x01 \x01(\x05R\x05Rcode\x12\x10\n" +
	"\x03Msg\x18\x02 \x01(\tR\x03Msg\"\x0f\n" +
	"\rWSDumpRequest\"L\n" +
	"\x0eWSDumpResponse\x12\x14\n" +
	"\x05Rcode\x18\x01 \x01(\x05R\x05Rcode\x12\x10\n" +
	"\x03Msg\x18\x02 \x01(\tR\x03Msg\x12\x12\n" +
	"\x04Json\x18\x03 \x01(\fR\x04Json2\x9f\x01\n" +
	"\x04sync\x12.\n" +
	"\x03Set\x12\x11.whoson.WSRequest\x1a\x12.whoson.WSResponse\"\x00\x12.\n" +
	"\x03Del\x12\x11.whoson.WSRequest\x1a\x12.whoson.WSResponse\"\x00\x127\n" +
	"\x04Dump\x12\x15.whoson.WSDumpRequest\x1a\x16.whoson.WSDumpResponse\"\x00B-Z+github.com/tai-ga/gowhoso/pkg/whoson;whosonb\x06proto3"

var (
	file_pkg_whoson_sync_proto_rawDescOnce sync.Once
	file_pkg_whoson_sync_proto_rawDescData []byte
)

func file_pkg_whoson_sync_proto_rawDescGZIP() []byte {
	file_pkg_whoson_sync_proto_rawDescOnce.Do(func() {
		file_pkg_whoson_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_whoson_sync_proto_rawDesc), len(file_pkg_whoson_sync_proto_rawDesc)))
	})
	return file_pkg_whoson_sync_proto_rawDescData
}

var file_pkg_whoson_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_whoson_sync_proto_goTypes = []any{
	(*WSRequest)(nil),      // 0: whoson.WSRequest
	(*WSResponse)(nil),     // 1: whoson.WSResponse
	(*WSDumpRequest)(nil),  // 2: whoson.WSDumpRequest
	(*WSDumpResponse)(nil), // 3: whoson.WSDumpResponse
}
var file_pkg_whoson_sync_proto_depIdxs = []int32{
	0, // 0: whoson.sync.Set:input_type -> whoson.WSRequest
	0, // 1: whoson.sync.Del:input_type -> whoson.WSRequest
	2, // 2: whoson.sync.Dump:input_type -> whoson.WSDumpRequest
	1, // 3: whoson.sync.Set:output_type -> whoson.WSResponse
	1, // 4: whoson.sync.Del:output_type -> whoson.WSResponse
	3, // 5: whoson.sync.Dump:output_type -> whoson.WSDumpResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_whoson_sync_proto_init() }
func file_pkg_whoson_sync_proto_init() {
	if File_pkg_whoson_sync_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_whoson_sync_proto_rawDesc), len(file_pkg_whoson_sync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_whoson_sync_proto_goTypes,
		DependencyIndexes: file_pkg_whoson_sync_proto_depIdxs,
		MessageInfos:      file_pkg_whoson_sync_proto_msgTypes,
	}.Build()
	File_pkg_whoson_sync_proto = out.File
	file_pkg_whoson_sync_proto_goTypes = nil
	file_pkg_whoson_sync_proto_depIdxs = nil
}
