on: [push, pull_request]
name: Build
jobs:
  test-build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        go-version: [1.17.x]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Test
      run: make test
    - name: Build
      run: make build
  coverage:
    runs-on: ubuntu-latest
    needs: test-build
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.16.x
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Test
      run: make test
    - name: coverage
      run: make cover
    - name: send codecov
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: bash <(curl -s https://codecov.io/bash)
  slack-notify:
    if: always()
    needs: [test-build, coverage]
    name: workflow notification to slack
    runs-on: ubuntu-latest
    steps:
      - uses: Gamesight/slack-workflow-status@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
